// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMhWZS8bBMDohEgUi7mTINAxHIIgiivvE',
    appId: '1:453724071260:web:5ee820276911611aff8d99',
    messagingSenderId: '453724071260',
    projectId: 'finwise-bdc0a',
    authDomain: 'finwise-bdc0a.firebaseapp.com',
    storageBucket: 'finwise-bdc0a.appspot.com',
    measurementId: 'G-PTFL1T7FQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMBUL-JyTZlcKM0P8uqtnHvwfA1Y0-UD4',
    appId: '1:453724071260:android:3f985c5351ab6987ff8d99',
    messagingSenderId: '453724071260',
    projectId: 'finwise-bdc0a',
    storageBucket: 'finwise-bdc0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiXj-J5IIrh0lvwfZIqYuAQWPul6no7co',
    appId: '1:453724071260:ios:caeb591b0973bb5cff8d99',
    messagingSenderId: '453724071260',
    projectId: 'finwise-bdc0a',
    storageBucket: 'finwise-bdc0a.appspot.com',
    iosBundleId: 'com.example.fintectBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiXj-J5IIrh0lvwfZIqYuAQWPul6no7co',
    appId: '1:453724071260:ios:682d87b66392eeb3ff8d99',
    messagingSenderId: '453724071260',
    projectId: 'finwise-bdc0a',
    storageBucket: 'finwise-bdc0a.appspot.com',
    iosBundleId: 'com.example.fintectBot.RunnerTests',
  );
}
